<a href="https://colab.research.google.com/github/Zukhrufaa-Memon/DSA_Lab_Task/blob/main/LAB_4_tasks(20sw076).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
even_arr=np.arange(2,33,2).reshape(4,4)
even_arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [ ]:
arr=np.arange(1,26).reshape(5,5)
condition=arr%2!=0
y=arr[condition]
y


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [ ]:
X = np.column_stack((np.ones(4), 2 * np.ones(4),3*np.ones(4),4*np.ones(4)))
X

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])